//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CargoConnectFinalAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CargoConnectEntity : DbContext
    {
        public CargoConnectEntity()
            : base("name=CargoConnectEntity")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admin { get; set; }
        public virtual DbSet<Bookings> Bookings { get; set; }
        public virtual DbSet<ChatMessages> ChatMessages { get; set; }
        public virtual DbSet<ChatThreads> ChatThreads { get; set; }
        public virtual DbSet<Checkpoints> Checkpoints { get; set; }
        public virtual DbSet<Customer> Customer { get; set; }
        public virtual DbSet<Driver> Driver { get; set; }
        public virtual DbSet<DriverDocuments> DriverDocuments { get; set; }
        public virtual DbSet<Notifications> Notifications { get; set; }
        public virtual DbSet<PackageAttributeMapping> PackageAttributeMapping { get; set; }
        public virtual DbSet<PackageAttributes> PackageAttributes { get; set; }
        public virtual DbSet<Packages> Packages { get; set; }
        public virtual DbSet<RecipientDetails> RecipientDetails { get; set; }
        public virtual DbSet<Requests> Requests { get; set; }
        public virtual DbSet<Reviews> Reviews { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<RoutePreferences> RoutePreferences { get; set; }
        public virtual DbSet<Routes> Routes { get; set; }
        public virtual DbSet<RouteSchedule> RouteSchedule { get; set; }
        public virtual DbSet<Shipments> Shipments { get; set; }
        public virtual DbSet<TripCheckpoints> TripCheckpoints { get; set; }
        public virtual DbSet<TripDelays> TripDelays { get; set; }
        public virtual DbSet<Trips> Trips { get; set; }
        public virtual DbSet<TripStats> TripStats { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<UserSuspensions> UserSuspensions { get; set; }
        public virtual DbSet<Vehicle> Vehicle { get; set; }
        public virtual DbSet<VehicleDocuments> VehicleDocuments { get; set; }
    }
}
