//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CargoConnectFinalAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RouteSchedule
    {
        public int routeScheduleId { get; set; }
        public int route_id { get; set; }
        public Nullable<System.DateTime> departureDate { get; set; }
        public Nullable<System.DateTime> arrivalDate { get; set; }
    
        public virtual Routes Routes { get; set; }
    }
}
