//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CargoConnectFinalAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shipments
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Shipments()
        {
            this.Bookings = new HashSet<Bookings>();
            this.ChatThreads = new HashSet<ChatThreads>();
            this.Packages = new HashSet<Packages>();
            this.RecipientDetails = new HashSet<RecipientDetails>();
            this.Requests = new HashSet<Requests>();
        }
    
        public int shipment_id { get; set; }
        public string sender_name { get; set; }
        public string sender_contact { get; set; }
        public string status { get; set; }
        public int customer_id { get; set; }
        public Nullable<bool> strict { get; set; }
        public Nullable<int> package_count { get; set; }
        public Nullable<double> total_weight { get; set; }
        public Nullable<double> pickup_lat { get; set; }
        public Nullable<double> pickup_long { get; set; }
        public string pickup_address { get; set; }
        public Nullable<double> delivery_lat { get; set; }
        public Nullable<double> delivery_long { get; set; }
        public string delivery_address { get; set; }
        public Nullable<System.DateTime> pickup_date { get; set; }
        public Nullable<double> shipment_radius { get; set; }
        public string shipment_type { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bookings> Bookings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChatThreads> ChatThreads { get; set; }
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Packages> Packages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecipientDetails> RecipientDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Requests> Requests { get; set; }
    }
}
